//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar_16x16 {
            get {
                object obj = ResourceManager.GetObject("Calendar_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Detail {
            get {
                object obj = ResourceManager.GetObject("Detail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoubleArrowLeftRight_16x16 {
            get {
                object obj = ResourceManager.GetObject("DoubleArrowLeftRight_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Edit_Copy {
            get {
                return ResourceManager.GetString("Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Edit_Cut {
            get {
                return ResourceManager.GetString("Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Edit_Paste {
            get {
                return ResourceManager.GetString("Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EhLibBrand32 {
            get {
                object obj = ResourceManager.GetObject("EhLibBrand32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit_ToolTip {
            get {
                return ResourceManager.GetString("Exit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderClosed {
            get {
                object obj = ResourceManager.GetObject("FolderClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Globe_North_America_16x16 {
            get {
                object obj = ResourceManager.GetObject("Globe_North_America_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string HelpAbout_ToolTip {
            get {
                return ResourceManager.GetString("HelpAbout_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_house_16x16 {
            get {
                object obj = ResourceManager.GetObject("home_house_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons_user_16x16 {
            get {
                object obj = ResourceManager.GetObject("icons_user_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jellyfish_small {
            get {
                object obj = ResourceManager.GetObject("jellyfish_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EhLib Main Complex Demo.
        /// </summary>
        internal static string MainForm_Caption {
            get {
                return ResourceManager.GetString("MainForm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellData is Link.
        /// </summary>
        internal static string MainForm_Demos_CellDataIsLink {
            get {
                return ResourceManager.GetString("MainForm_Demos_CellDataIsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different editors in one column.
        /// </summary>
        internal static string MainForm_Demos_DiferentEditor {
            get {
                return ResourceManager.GetString("MainForm_Demos_DiferentEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Grid.
        /// </summary>
        internal static string MainForm_Demos_MainGrid {
            get {
                return ResourceManager.GetString("MainForm_Demos_MainGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master/Detail.
        /// </summary>
        internal static string MainForm_Demos_MasterDetail {
            get {
                return ResourceManager.GetString("MainForm_Demos_MasterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demos.
        /// </summary>
        internal static string MainForm_Demos_Page {
            get {
                return ResourceManager.GetString("MainForm_Demos_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Grid.
        /// </summary>
        internal static string MainForm_Demos_PropertyGrid {
            get {
                return ResourceManager.GetString("MainForm_Demos_PropertyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows AutoExpand.
        /// </summary>
        internal static string MainForm_Demos_RowsAutoExpent {
            get {
                return ResourceManager.GetString("MainForm_Demos_RowsAutoExpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Box.
        /// </summary>
        internal static string MainForm_Demos_SearchBox {
            get {
                return ResourceManager.GetString("MainForm_Demos_SearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MainForm_MenuAbout {
            get {
                return ResourceManager.GetString("MainForm_MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainForm_MenuExit {
            get {
                return ResourceManager.GetString("MainForm_MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MainForm_MenuFile {
            get {
                return ResourceManager.GetString("MainForm_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MainForm_MenuLanguage {
            get {
                return ResourceManager.GetString("MainForm_MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        internal static string MainForm_Solutions_Page {
            get {
                return ResourceManager.GetString("MainForm_Solutions_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EhLib Main Demo. Shows All Major Features and Functions of the Library.
        /// </summary>
        internal static string MainForm_StatusBarInfo {
            get {
                return ResourceManager.GetString("MainForm_StatusBarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string MainGrid_Customer_Title {
            get {
                return ResourceManager.GetString("MainGrid_Customer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        internal static string MainGrid_Dates_Title {
            get {
                return ResourceManager.GetString("MainGrid_Dates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string MainGrid_Employee_Title {
            get {
                return ResourceManager.GetString("MainGrid_Employee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight.
        /// </summary>
        internal static string MainGrid_Freight_Title {
            get {
                return ResourceManager.GetString("MainGrid_Freight_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string MainGrid_ID_Title {
            get {
                return ResourceManager.GetString("MainGrid_ID_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MainGrid_Name_Title {
            get {
                return ResourceManager.GetString("MainGrid_Name_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string MainGrid_OrderID_Title {
            get {
                return ResourceManager.GetString("MainGrid_OrderID_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string MainGrid_Required_Title {
            get {
                return ResourceManager.GetString("MainGrid_Required_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string MainGrid_Shipped_Title {
            get {
                return ResourceManager.GetString("MainGrid_Shipped_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper ID.
        /// </summary>
        internal static string MainGrid_ShipperId_Title {
            get {
                return ResourceManager.GetString("MainGrid_ShipperId_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipper Name.
        /// </summary>
        internal static string MainGrid_ShipperName_Title {
            get {
                return ResourceManager.GetString("MainGrid_ShipperName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap man_with_tai {
            get {
                object obj = ResourceManager.GetObject("man_with_tai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Master {
            get {
                object obj = ResourceManager.GetObject("Master", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print preview.
        /// </summary>
        internal static string PrintPreview_ToolTip {
            get {
                return ResourceManager.GetString("PrintPreview_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use/Unuse Visual Styles.
        /// </summary>
        internal static string RightToLeft_LeftToRightDirection_ToolTip {
            get {
                return ResourceManager.GetString("RightToLeft_LeftToRightDirection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap themes {
            get {
                object obj = ResourceManager.GetObject("themes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left direction/Left to right direction.
        /// </summary>
        internal static string UseUnuseVisualStyles_ToolTip {
            get {
                return ResourceManager.GetString("UseUnuseVisualStyles_ToolTip", resourceCulture);
            }
        }
    }
}
